import { createHash } from 'node:crypto';

import { publishedQuestionManifestSchema } from '@agentprep/question-schema';

export interface ManifestSource {
  file: string;
  text: string;
}

function escapeCell(value: string) {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

export function buildProvenanceReport(sources: readonly ManifestSource[]) {
  const manifests = [...sources]
    .sort((left, right) => left.file.localeCompare(right.file))
    .map((source) => ({
      file: source.file,
      sha256: createHash('sha256').update(source.text).digest('hex'),
      manifest: publishedQuestionManifestSchema.parse(JSON.parse(source.text) as unknown),
    }));
  const questions = manifests.flatMap(({ file, manifest }) =>
    manifest.questions.map((question) => ({ file, question })),
  );
  const licenses = [
    ...new Set(questions.map(({ question }) => question.provenance.license)),
  ].sort();
  const kinds = [...new Set(questions.map(({ question }) => question.provenance.kind))].sort();

  const lines = [
    '# Content Provenance Report',
    '',
    '> Generated by `pnpm content:report`. Do not edit manually.',
    '',
    '## Summary',
    '',
    `- Published manifests: ${manifests.length}`,
    `- Reviewed questions: ${questions.length}`,
    `- Source kinds: ${kinds.join(', ') || 'none'}`,
    `- Licenses: ${licenses.join(', ') || 'none'}`,
    '',
    '## Manifest integrity',
    '',
    '| Manifest | Content version | Questions | SHA-256 |',
    '| --- | --- | ---: | --- |',
    ...manifests.map(
      ({ file, manifest, sha256 }) =>
        `| ${escapeCell(file)} | ${escapeCell(manifest.contentVersion)} | ${manifest.questions.length} | \`${sha256}\` |`,
    ),
    '',
    '## Question provenance',
    '',
    '| Question ID | Source | Source version | License | Transform | Status |',
    '| --- | --- | --- | --- | --- | --- |',
    ...questions.map(
      ({ question }) =>
        `| ${escapeCell(question.id)} | ${escapeCell(question.provenance.source)} | ${escapeCell(question.provenance.sourceVersion)} | ${escapeCell(question.provenance.license)} | ${escapeCell(question.provenance.transform)} | ${question.provenance.reviewStatus} |`,
    ),
    '',
  ];
  return lines.join('\n');
}
